yarnPath: .yarn/releases/yarn-3.5.1.cjs
nodeLinker: node-modules
packageExtensions:
  "@lerna/legacy-package-management@*":
    peerDependenciesMeta:
      "@lerna/child-process":
        optional: false
      "js-yaml":
        optional: false
      "rimraf":
        optional: false
  "@nrwl/devkit@*":
    dependencies:
      "nx": "16.*"
