version: 2.1

aliases:
  - &docker-node-image
    - image: cimg/node:18.16

  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

  # - &restore-pnpm-global-store
  #   name: Restore pnpm cache
  #   key: pnpm-cache-v1

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
        - node_modules
    key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

  # - &save-pnpm-global-store
  #   name: Save pnpm cache
  #   paths:
  #       - ~/.local/share/pnpm/store
  #   key: pnpm-cache-v1

jobs:
  checkout-code:
    docker: *docker-node-image
    steps:
      - checkout
      # - restore_cache: *restore-pnpm-global-store
      - restore_cache: *restore-node-modules-cache
      - run: corepack enable
      - run: pnpm install
      - save_cache: *save-node-modules-cache
      # - save_cache: *save-pnpm-global-store
      - persist_to_workspace:
          root: "."
          paths: [packages/*/node_modules]

  build:
    docker: *docker-node-image
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: yarn compile
      - persist_to_workspace:
          root: "."
          paths:
            - packages/*/lib
            - packages/*/dist

workflows:
  build:
    jobs:
      - checkout-code
      - build:
          requires: [checkout-code]
