version: 2.1

aliases:
  - &docker-node-image
    - image: cimg/node:20.8

  - &save-node-modules-cache
    name: Save node_modules cache
    paths:
      - node_modules
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &restore-node-modules-cache
    name: Restore node_modules cache
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    name: Save yarnpkg cache
    paths:
      - .yarn/cache
    key: yarn-cache-v1

  - &restore-yarn-cache
    name: Restore yarnpkg cache
    key: yarn-cache-v1

jobs:
  checkout-code:
    docker: *docker-node-image
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - restore_cache: *restore-node-modules-cache
      - run: sudo corepack enable
      - run: yarn
      - save_cache: *save-node-modules-cache
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: "."
          paths: [packages/*/node_modules]

  build:
    docker: *docker-node-image
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: sudo corepack enable
      - run: yarn build
      - persist_to_workspace:
          root: "."
          paths:
            - packages/*/lib
            - packages/*/dist

  check:
    docker: *docker-node-image
    steps:
      - checkout
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: sudo corepack enable
      - run: yarn check

  dist:
    docker: *docker-node-image
    environment:
      DENO_INSTALL_PATH: /home/circleci/.deno
    steps:
      - checkout
      - run:
          name: Install @electron-forge/maker-deb Linux dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot
      - restore_cache: *restore-node-modules-cache
      - attach_workspace: { at: "." }
      - run: sudo corepack enable
      - run:
          name: Install Deno & add to PATH
          command: |
            curl -fsSL https://deno.land/install.sh | sh
            echo 'export PATH=$DENO_INSTALL_PATH:"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
      - run: yarn dist

workflows:
  build-check:
    jobs:
      - checkout-code
      - build:
          requires: [checkout-code]
      - check:
          requires: [checkout-code]
      - dist:
          requires: [build]
