// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/raga-app/CommandBar.tsx": () => import("../components/mockups/raga-app/CommandBar.tsx"),
  "./components/mockups/raga-app/CommandBarDocked.tsx": () => import("../components/mockups/raga-app/CommandBarDocked.tsx"),
  "./components/mockups/raga-app/CommandBarFloating.tsx": () => import("../components/mockups/raga-app/CommandBarFloating.tsx"),
  "./components/mockups/raga-app/Curator.tsx": () => import("../components/mockups/raga-app/Curator.tsx"),
  "./components/mockups/raga-app/Studio.tsx": () => import("../components/mockups/raga-app/Studio.tsx")
};
