/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function convertSwinsianTrackToMusicAppTrack(track: TrackDefinition): MusicAppTrackDefinition
export interface BasicTrackDefinition {
  trackId: number
  persistentId: string
  location: string
}
export interface TrackDefinition {
  trackId: number
  persistentId: string
  location: string
  bitRate?: number
  bpm?: number
  playCount?: number
  rating?: number
  sampleRate?: number
  size?: number
  totalTime?: number
  trackNumber?: number
  volumeAdjustment?: number
  year?: number
  albumArtist?: string
  album?: string
  artist?: string
  genre?: string
  grouping?: string
  name?: string
  trackType?: string
  dateAdded?: string
  dateModified?: string
}
export interface MusicAppTrackDefinition {
  base: TrackDefinition
  artworkCount?: number
  fileFolderCount?: number
  libraryFolderCount?: number
  kind?: string
  normalization?: number
  loved?: boolean
}
export interface PlaylistItem {
  trackId: number
}
export interface PlaylistDefinition {
  allItems?: boolean
  description?: string
  master?: boolean
  name: string
  parentPersistentId?: string
  playlistId: string
  playlistItems: Array<PlaylistItem>
  playlistPersistentId: string
  visible?: boolean
}
export declare function convertSwinsianToItunesXml(tracks: unknown[], playlists: unknown[]): string
